export const categories = [
	{ label: 'Cycle', value: 1 },
	{ label: 'Cycle ( 3 Wheels )', value: 2 },
	{ label: 'Car', value: 3 },
	{ label: 'Bus ( City )', value: 4 },
	{ label: 'Bus ( High Way )', value: 5 },
	{ label: 'Light Truck ( City )', value: 6 },
	{ label: 'Light Truck ( High way )', value: 7 },
	{ label: 'Heavy Truck ( City )', value: 8 },
	{ label: 'Heavy Truck ( High way )', value: 9 },
	{ label: 'Trailer ( City )', value: 10 },
	{ label: 'Trailer ( High way )', value: 11 },
	{ label: 'Htawlargyi', value: 12 },
	{ label: 'Tractor', value: 13 },
	{ label: 'Small Tractor', value: 14 },
	{ label: 'Heavy Machinery', value: 15 },
	{ label: 'Commercial Vehicle', value: 16 },
	{ label: 'Phone Tower', value: 17 },
	{ label: 'Industrial Zone', value: 18 },
	{ label: 'Generator Industry', value: 19 },
	{ label: 'Agriculture Machine', value: 20 },
	{ label: 'Generator ( Home Use )', value: 21 },
	{ label: 'Hospital', value: 22 },
	{ label: 'School', value: 23 },
	{ label: 'Super Market', value: 24 },
	{ label: 'Hotel', value: 25 },
	{ label: 'Housing', value: 26 },
	{ label: 'Boat', value: 27 },
	{ label: 'Pump Test', value: 28 },
	{ label: 'Office Use ( Bowser Car )', value: 29 },
	{ label: 'Station Use', value: 30 },
]

export const paymentType = [
	{
		id: 1,
		label: 'Cash',
		value: 'Cash',
		iconName: 'cash',
	},
	{
		id: 2,
		label: 'KBZ_Pay',
		value: 'KBZ_Pay',
		iconName: 'cellphone',
	},
	{
		id: 3,
		label: 'Credit',
		value: 'Credit',
		iconName: 'credit-card',
	},
	{
		id: 4,
		label: 'Debt',
		value: 'Debt',
		iconName: 'cash-minus',
	},
	{
		id: 5,
		label: 'FOC',
		value: 'FOC',
		iconName: 'office-building',
	},
	{
		id: 6,
		label: 'Others',
		value: 'Others',
		iconName: 'more',
	},
]
